### PR TITLE
Add tests and tests-per-million data

### LINKED ISSUE #79: Add "Tests" and "Tests Per Million" data from API
It would be cool if we can add tests/test-per-million numbers in the data table.

### PR DESCRIPTION
**Pull request by surgeharb**
Fixes ahmadawais/corona-cli#79

### CODE REVIEW

**Review by ahmadawais — CHANGES_REQUESTED** [review]
This makes the table way too long and not many screens display it OK then. So, I'm not sure if I want this in there. Maybe behind a flag for only people that need it?

**Comment by surgeharb** [comment]
Definitely a good idea to add it behind a flag.

**Comment by surgeharb** [comment]
Okay @ahmadawais , now I have implemented a dynamic way to add custom fields to the table without being hard-coded in the table head. This change is not limited to tests and testsPerOneMillion only.

**Comment by surgeharb** [comment]
I hope these changes would make a good improvement for the future of this cli (dynamic table columns).

**Pull request closed without merging**
