### PR TITLE
🐛 FIX: Sorting China

### PR DESCRIPTION
**Pull request by nezia1**
Fixed issue #68.
 The API ordered everything descending by default, except China for some reason.
Edit: I just noticed that I tagged the wrong issue when committing, could you change that?

### CODE REVIEW

**Comment by marvinjude** [comment]
Hi @Nezia1 you can edit the comment to point to the right issue.

**Comment by ahmadawais** [comment]
This would make the call slow, it would be reordering all data and then limiting it. Can we improve that? What's the issue there? Why is it happening? I haven't dug deep

**Comment by nezia1** [comment]
The issue is basically that the API orders by default in a descending order, but places China at the bottom for some reason. I don't think we have much choice here, unless we can find a more optimal way of doing it?

**Review by ahmadawais — APPROVED** [review]
Looks good to me! ✔︎

**Comment by ahmadawais** [comment]
Thank you! 👌

**Comment by ahmadawais** [comment]
🔗 https://github.com/ahmadawais/corona-cli/releases/tag/4.0.0
🔗 https://www.npmjs.com/package/corona-cli

**Comment by nezia1** [comment]
No problem! 😊

**Pull request merged**
